---
- name: Add Docker repository key
  apt_key: keyserver="{{ apt_key_keyserver }}" id="{{ apt_key_id }}"

- name: Add Docker repository
  apt_repository: repo="{{ apt_repository_repo }}" state=present

- name: Install docker package
  apt:
    name: "{{ docker_package_name }}"
    state: "{{ docker_package_state }}"
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Install certificates
  register: certificates
  copy:
    src="./certs/docker/"
    dest="/etc/docker/"

- name: Generate certificates
  command: chdir=/etc/docker/ {{ item }}
  when: certificates.changed
  with_items:
  - openssl genrsa -out server-key.pem 2048
  - openssl req -subj "/CN={{ hostname }}" -new -key server-key.pem -out server-request.csr
  - openssl x509 -req -days 3650 -in server-request.csr -CA ca.pem -CAkey CAkey.pem -CAcreateserial -out server.pem -extensions v3_req -extfile openssl.cnf
  - openssl rsa -in server-key.pem -out server-key.pem
  - rm CAkey.pem ca.srl openssl.cnf server-request.csr

- name: "Add docker default opts to Upstart"
  register: configuration
  template: "src=daemon.conf.j2  dest=/etc/default/docker"

- name: Restart the docker service
  when: certificates.changed or configuration.changed
  service:
      name=docker
      state=restarted
